<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\core\Shared.Domain\Shared.Domain.csproj" />
  </ItemGroup>

</Project>
