<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\image_2025-11-08_20-30-02.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ApiConf.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\image_2025-11-08_20-30-02.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DryIoc.Microsoft.DependencyInjection.Extension" Version="1.0.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\clients\modules\wpf\NorthwindPlatform.Modules.Authentication.Wpf\NorthwindPlatform.Modules.Authentication.Wpf.csproj" />
    <ProjectReference Include="..\..\..\clients\shared\ui\Shared.UI.Wpf\Shared.UI.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ApiConf.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
