<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f5fbaf59-3b26-4728-a7c9-f176a62af7f0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NorthwindPlatform.Staff.Service.Application\NorthwindPlatform.Staff.Service.Application.csproj" />
    <ProjectReference Include="..\NorthwindPlatform.Staff.Service.Infrastructure.KurrentDB\NorthwindPlatform.Staff.Service.Infrastructure.KurrentDB.csproj" />
    <ProjectReference Include="..\NorthwindPlatform.Staff.Service.Infrastructure.PostgreSQL\NorthwindPlatform.Staff.Service.Infrastructure.PostgreSQL.csproj" />
    <ProjectReference Include="..\NorthwindPlatform.Staff.Service.Infrastructure.Projections\NorthwindPlatform.Staff.Service.Infrastructure.Projections.csproj" />
  </ItemGroup>

</Project>
