<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Quantropic.Security.Srp.Client" Version="0.2.0-beta.1" />
    <PackageVersion Include="Quantropic.Security.Windows" Version="0.2.0-beta.1" />

    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5"/>

    <PackageVersion Include="DryIoc.Microsoft.DependencyInjection.Extension" Version="1.0.0.2" />
    <PackageVersion Include="Prism.DryIoc" Version="9.0.537" />
    <PackageVersion Include="Prism.Wpf" Version="9.0.537" />
    <PackageVersion Include="Prism.Core" Version="9.0.537" />

    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />

    <PackageVersion Include="MediatR" Version="14.0.0"/>
    <PackageVersion Include="Dapper" Version="2.1.66"/>
    <PackageVersion Include="FluentValidation" Version="12.0.0"/>
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0"/>

    <PackageVersion Include="KurrentDB.Client" Version="1.3.1"/>
    <PackageVersion Include="Npgsql" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.0"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />

    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0"/>
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1"/>
    <PackageVersion Include="Serilog.Enrichers.Thread" Version="4.0.0"/>
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0"/>
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0"/>
    <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0"/>
  </ItemGroup>
</Project>