<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Services\Dialog\" />
    <Folder Include="Services\FileDialog\" />
    <Folder Include="UserControls\" />
    <Folder Include="Attachables\" />
    <Folder Include="UserControls\" />
    <Folder Include="Attachables\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>

</Project>
