<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\api\NorthwindPlatform.Authentication.ApiClient\NorthwindPlatform.Authentication.ApiClient.csproj" />
    
    <ProjectReference Include="..\..\..\shared\core\security\Shared.Client.Security.Abstractions\Shared.Client.Security.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\shared\core\security\Shared.Client.Security.Cryptography\Shared.Client.Security.Cryptography.csproj" />
    <ProjectReference Include="..\..\..\shared\core\security\Shared.Client.Security.Srp\Shared.Client.Security.Srp.csproj" />
    <ProjectReference Include="..\..\..\shared\core\security\Shared.Client.Security.Utilities\Shared.Client.Security.Utilities.csproj" />
    <ProjectReference Include="..\..\..\shared\core\security\Shared.Client.Security.Windows\Shared.Client.Security.Windows.csproj" />
    
    <ProjectReference Include="..\..\..\shared\ui\Shared.UI.Wpf\Shared.UI.Wpf.csproj" />
  </ItemGroup>

</Project>
