<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="Quantropic.Security.Srp.Client" Version="0.1.0-beta.2" />
    <PackageReference Include="Quantropic.Security.Windows" Version="0.1.0-beta.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\api\NorthwindPlatform.Authentication.ApiClient\NorthwindPlatform.Authentication.ApiClient.csproj" />
    <ProjectReference Include="..\..\..\shared\ui\Shared.UI.Wpf\Shared.UI.Wpf.csproj" />
  </ItemGroup>

</Project>
