<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>74f7a729-7be9-426a-bc19-25082b7731de</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
