<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ae7f0654-0cc0-41c0-8082-69df7b4d5e8e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
